services:
  home-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: homebase
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  postgres:
  pgadmin:
