name: java application build
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        maven: [ '3.8.7']
        os: ['windows-latest','ubuntu-latest']
    name: Maven ${{ matrix.maven }} sample
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 17
          maven-version: ${{ matrix.maven }}
      - run: mvn package -DskipTests -X
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: ksnavinkumar/logical-ctc
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
